# All section identifiers with the corresponding numbers
TOP_LEFT = 0
TOP_MIDDLE = 1
TOP_RIGHT = 2
MIDDLE_LEFT = 3
CENTER = 4
MIDDLE_RIGHT = 5
BOTTOM_LEFT = 6
BOTTOM_MIDDLE = 7
BOTTOM_RIGHT = 8
INNER_BOTTOM_LEFT = 9
INNER_BOTTOM_RIGHT = 10
INNER_TOP_LEFT = 11
INNER_TOP_RIGHT = 12

# The width of a single section
TILE_WIDTH = 64
